// spec: ROOT/tech_design/internal/frontmatter@v27

// Package frontmatter reads and parses the YAML frontmatter block from spec
// nodes, test nodes, and external dependency files.
//
// Spec ref: ROOT/tech_design/internal/frontmatter § "Intent"
//
// The frontmatter is the YAML block delimited by the first and second `---`
// markers at the top of the file. Everything after the second `---` is
// intentionally ignored — the file body is never read.
//
// Spec ref: ROOT/tech_design/internal/frontmatter § "Parsing"
package frontmatter

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	// Spec ref: ROOT/tech_design/internal/frontmatter § "YAML dependency"
	// Uses github.com/goccy/go-yaml — drop-in replacement for gopkg.in/yaml.v3.
	"github.com/goccy/go-yaml"
)

// DependsOn represents a single entry in the `depends_on` frontmatter field.
//
// Spec ref: ROOT/tech_design/internal/frontmatter § "DependsOn structure"
//
// YAML key mapping:
//   - `path`   → LogicalName  (logical name of the dependency; required)
//   - `filter` → Filter       (glob patterns for file selection; optional)
type DependsOn struct {
	// LogicalName is the logical name of the dependency node (YAML key: "path").
	LogicalName string `yaml:"path"`

	// Filter holds optional glob patterns for selecting files within an
	// external dependency folder (YAML key: "filter").
	Filter []string `yaml:"filter"`
}

// Frontmatter holds the parsed fields extracted from a spec file's YAML
// frontmatter block.
//
// Spec ref: ROOT/tech_design/internal/frontmatter § "Parsing"
//
// All fields are optional at the parsing level — validation of required
// fields happens elsewhere. Unknown YAML fields are silently ignored.
//
// Spec ref: EXTERNAL/goccy-go-yaml § "Unmarshal" (unknown fields ignored by default)
type Frontmatter struct {
	// DependsOn is the list of cross-tree dependencies declared by the node.
	// Spec ref: ROOT/tech_design/internal/frontmatter § "DependsOn structure"
	DependsOn []DependsOn `yaml:"depends_on"`

	// Implements is the list of source file paths generated by this node,
	// relative to the project root.
	Implements []string `yaml:"implements"`
}

// rawFrontmatter is an internal struct used for YAML unmarshalling. It mirrors
// the YAML structure of the frontmatter block. Fields not needed by callers
// (e.g., version, parent_version) are omitted — unknown fields are ignored by
// the YAML library.
//
// Spec ref: ROOT/tech_design/internal/frontmatter § "Parsing"
type rawFrontmatter struct {
	DependsOn  []DependsOn `yaml:"depends_on"`
	Implements []string    `yaml:"implements"`
}

// ParseFrontmatter reads the file at filePath, extracts the YAML frontmatter
// block (between the first and second `---` delimiters), and returns the
// parsed result.
//
// Spec ref: ROOT/tech_design/internal/frontmatter § "Interface"
//
// Efficiency: reads the file line by line and stops immediately after the
// closing `---` is found. The file body is never read.
//
// Spec ref: ROOT/tech_design/internal/frontmatter § "Efficiency"
//
// ParseFrontmatter does not cache results — caching is the caller's
// responsibility.
//
// Error messages follow the exact formats mandated by the spec:
//   - "error reading <path>: <underlying error>"
//   - "error parsing frontmatter in <path>: <underlying error>"
//   - "frontmatter not found in <path>"
//
// Spec ref: ROOT/tech_design/internal/frontmatter § "Error handling"
func ParseFrontmatter(filePath string) (*Frontmatter, error) {
	// Open the file for line-by-line reading.
	// Spec ref: ROOT/tech_design/internal/frontmatter § "Efficiency"
	f, err := os.Open(filePath)
	if err != nil {
		// Spec ref: ROOT/tech_design/internal/frontmatter § "Error handling"
		return nil, fmt.Errorf("error reading %s: %w", filePath, err)
	}
	defer f.Close() //nolint:errcheck // closing a read-only file; error irrelevant

	// State machine for extracting the frontmatter block:
	//   - inBlock=false: looking for the opening `---`
	//   - inBlock=true:  accumulating YAML lines until the closing `---`
	var (
		inBlock bool
		lines   []string
	)

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()

		if !inBlock {
			// The first `---` opens the frontmatter block.
			if strings.TrimRight(line, "\r") == "---" {
				inBlock = true
			}
			// Lines before the first `---` are ignored (there should be none
			// for well-formed spec files, but we skip them gracefully).
			continue
		}

		// The second `---` closes the frontmatter block. Stop reading
		// immediately — the file body is never consumed.
		// Spec ref: ROOT/tech_design/internal/frontmatter § "Efficiency"
		if strings.TrimRight(line, "\r") == "---" {
			// Successfully extracted the frontmatter block; proceed to parse.
			raw := &rawFrontmatter{}

			yamlBlock := strings.Join(lines, "\n")
			if err := yaml.Unmarshal([]byte(yamlBlock), raw); err != nil {
				// Spec ref: ROOT/tech_design/internal/frontmatter § "Error handling"
				return nil, fmt.Errorf("error parsing frontmatter in %s: %w", filePath, err)
			}

			return &Frontmatter{
				DependsOn:  raw.DependsOn,
				Implements: raw.Implements,
			}, nil
		}

		// Accumulate YAML content lines within the block.
		lines = append(lines, line)
	}

	// Check for scanner errors (e.g., I/O error mid-read).
	// Spec ref: ROOT/tech_design § "Constraints" — every error return must be checked.
	if err := scanner.Err(); err != nil {
		// Spec ref: ROOT/tech_design/internal/frontmatter § "Error handling"
		return nil, fmt.Errorf("error reading %s: %w", filePath, err)
	}

	// Reached end of file without finding a closing `---`. This covers both
	// the case where the opening `---` was never found and the case where it
	// was found but the block was never closed.
	// Spec ref: ROOT/tech_design/internal/frontmatter § "Error handling"
	return nil, fmt.Errorf("frontmatter not found in %s", filePath)
}
