// code-from-spec: ROOT/tech_design/internal/frontmatter@v36

// Package frontmatter reads and parses YAML frontmatter from spec nodes,
// test nodes, and external dependency files.
//
// It reads line by line and stops as soon as the closing "---" delimiter is
// found, so the file body is never read.
package frontmatter

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/goccy/go-yaml"
)

// DependsOn represents a single entry in the depends_on list.
// LogicalName maps to the "path" YAML key; Version is the known version of
// that dependency.
type DependsOn struct {
	LogicalName string
	Version     int
}

// Frontmatter holds the parsed frontmatter fields from a spec node,
// test node, or external dependency file.
type Frontmatter struct {
	// Version is the node's own version. Required; ParseFrontmatter returns
	// ErrMissingVersion if this field is absent or zero.
	Version int

	// ParentVersion is the version of the parent node this node was written
	// against. Nil if the field is absent (e.g. root node, test nodes).
	ParentVersion *int

	// SubjectVersion is the version of the subject node a test node was written
	// against. Nil if the field is absent (non-test nodes).
	SubjectVersion *int

	// DependsOn lists cross-tree dependencies declared in the frontmatter.
	DependsOn []DependsOn

	// Implements lists output source files generated by this node.
	// Paths are relative to the project root.
	Implements []string
}

// Sentinel errors. All errors returned by ParseFrontmatter wrap one of these
// so callers can use errors.Is() to distinguish error categories.
var (
	// ErrRead is returned when the file cannot be opened or read.
	ErrRead = errors.New("error reading file")

	// ErrFrontmatterParse is returned when the YAML frontmatter block is
	// malformed.
	ErrFrontmatterParse = errors.New("error parsing frontmatter")

	// ErrFrontmatterMissing is returned when no "---" delimiters are found at
	// the top of the file (opening delimiter absent, or closing delimiter never
	// encountered).
	ErrFrontmatterMissing = errors.New("frontmatter not found")

	// ErrMissingVersion is returned when the version field is absent or zero.
	ErrMissingVersion = errors.New("version field is required")
)

// rawDependsOn mirrors the YAML structure of a single depends_on entry.
// The "path" key maps to the logical name of the dependency.
type rawDependsOn struct {
	Path    string `yaml:"path"`
	Version int    `yaml:"version"`
}

// rawFrontmatter mirrors the complete YAML frontmatter block for
// unmarshalling. Unknown fields are silently ignored by goccy/go-yaml.
type rawFrontmatter struct {
	Version        int            `yaml:"version"`
	ParentVersion  *int           `yaml:"parent_version"`
	SubjectVersion *int           `yaml:"subject_version"`
	DependsOn      []rawDependsOn `yaml:"depends_on"`
	Implements     []string       `yaml:"implements"`
}

// ParseFrontmatter reads the file at filePath, extracts the YAML frontmatter
// block (the content between the first "---" and the second "---" at the top
// of the file), parses it, and returns the result.
//
// The file is read line by line. Parsing stops as soon as the closing "---"
// is found — the file body beyond the frontmatter is never read.
//
// All returned errors wrap one of the sentinel variables (ErrRead,
// ErrFrontmatterParse, ErrFrontmatterMissing, ErrMissingVersion) so callers
// can use errors.Is() to distinguish error categories.
func ParseFrontmatter(filePath string) (*Frontmatter, error) {
	f, err := os.Open(filePath)
	if err != nil {
		return nil, fmt.Errorf("%w: %s: %v", ErrRead, filePath, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)

	// Step 1: Advance to the opening "---" delimiter.
	// The opening delimiter must appear at the very top of the file.
	// Any non-empty, non-delimiter line before the first "---" means the file
	// has no frontmatter.
	foundOpen := false
	for scanner.Scan() {
		line := scanner.Text()
		if line == "---" {
			foundOpen = true
			break
		}
		// Non-empty content before the opening delimiter — no frontmatter.
		if strings.TrimSpace(line) != "" {
			break
		}
	}
	if scanErr := scanner.Err(); scanErr != nil {
		return nil, fmt.Errorf("%w: %s: %v", ErrRead, filePath, scanErr)
	}
	if !foundOpen {
		return nil, fmt.Errorf("%w: %s", ErrFrontmatterMissing, filePath)
	}

	// Step 2: Collect lines between the opening "---" and the closing "---".
	var lines []string
	foundClose := false
	for scanner.Scan() {
		line := scanner.Text()
		if line == "---" {
			foundClose = true
			break
		}
		lines = append(lines, line)
	}
	if scanErr := scanner.Err(); scanErr != nil {
		return nil, fmt.Errorf("%w: %s: %v", ErrRead, filePath, scanErr)
	}
	if !foundClose {
		// The closing "---" was never encountered — frontmatter is incomplete.
		return nil, fmt.Errorf("%w: %s", ErrFrontmatterMissing, filePath)
	}

	// Step 3: Parse the collected YAML content.
	yamlContent := strings.Join(lines, "\n")
	var raw rawFrontmatter
	if unmarshalErr := yaml.Unmarshal([]byte(yamlContent), &raw); unmarshalErr != nil {
		return nil, fmt.Errorf("%w: %s: %v", ErrFrontmatterParse, filePath, unmarshalErr)
	}

	// Step 4: Validate required fields.
	// Version zero means the field was absent or explicitly set to zero —
	// both are invalid per the spec.
	if raw.Version == 0 {
		return nil, fmt.Errorf("%w: %s", ErrMissingVersion, filePath)
	}

	// Step 5: Map raw YAML structs to the exported Frontmatter type.
	// The depends_on "path" key becomes LogicalName in the public type.
	result := &Frontmatter{
		Version:        raw.Version,
		ParentVersion:  raw.ParentVersion,
		SubjectVersion: raw.SubjectVersion,
		Implements:     raw.Implements,
	}
	for _, dep := range raw.DependsOn {
		result.DependsOn = append(result.DependsOn, DependsOn{
			LogicalName: dep.Path,
			Version:     dep.Version,
		})
	}

	return result, nil
}
