// spec: ROOT/tech_design/internal/frontmatter@v23

// Package frontmatter reads and parses the YAML frontmatter block from spec
// nodes, test nodes, and external dependency files.
//
// Frontmatter is the YAML content between the first "---" and the second "---"
// at the top of the file. Everything after the closing "---" is ignored.
//
// This package only extracts the fields relevant to the code-from-spec
// toolchain (depends_on, implements). All other YAML fields are silently
// ignored. Validation of required fields is the caller's responsibility.
package frontmatter

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/goccy/go-yaml"
)

// DependsOn represents a single entry in the depends_on list of a spec node.
//
// LogicalName is the logical name of the dependency (e.g. "EXTERNAL/database"
// or "ROOT/payments/fees"). Filter is an optional set of glob patterns used
// to select a subset of files within an external dependency folder; it applies
// only to EXTERNAL/ dependencies and is ignored otherwise.
type DependsOn struct {
	// LogicalName is the "path" field in the YAML — the dependency's logical
	// name as defined by the Code from Spec framework.
	LogicalName string `yaml:"path"`

	// Filter is an optional list of glob patterns (relative to the external
	// dependency folder). When non-empty, only files matching at least one
	// pattern are imported (plus _external.md, which is always included).
	Filter []string `yaml:"filter"`
}

// Frontmatter holds the fields extracted from a spec node's YAML frontmatter.
// All fields are optional at the parsing level — validation happens elsewhere.
type Frontmatter struct {
	// DependsOn lists all cross-tree dependencies declared by this node.
	DependsOn []DependsOn `yaml:"depends_on"`

	// Implements lists the source files generated by this node.
	// Paths are relative to the project root.
	Implements []string `yaml:"implements"`
}

// ParseFrontmatter reads the file at filePath, extracts the YAML frontmatter
// block (between the first "---" line and the second "---" line), and returns
// the parsed result.
//
// The parser reads the file line by line and stops as soon as the closing
// "---" is found — the file body is never read into memory, keeping this
// efficient even for large spec files.
//
// Caching is the caller's responsibility; this function always reads from disk.
//
// Errors returned:
//
//	"error reading <path>: <underlying error>"
//	"error parsing frontmatter in <path>: <underlying error>"
//	"frontmatter not found in <path>"
func ParseFrontmatter(filePath string) (*Frontmatter, error) {
	f, err := os.Open(filePath)
	if err != nil {
		return nil, fmt.Errorf("error reading %s: %w", filePath, err)
	}
	defer f.Close()

	// Step 1 — scan line by line collecting the frontmatter block.
	//
	// State machine:
	//   beforeOpen  — haven't seen the opening "---" yet
	//   insideBlock — past opening "---", collecting YAML lines
	//   done        — saw the closing "---"; stop reading
	const (
		beforeOpen  = iota
		insideBlock // collecting YAML content
		done
	)

	state := beforeOpen
	var yamlLines []string

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()

		switch state {
		case beforeOpen:
			// The very first non-empty content line must be "---".
			// Blank lines before the opening delimiter are tolerated.
			if strings.TrimSpace(line) == "---" {
				state = insideBlock
			}
			// Any other non-blank line means there is no frontmatter.
			// We keep scanning until we confirm or deny the "---" opener
			// — but once we see a non-"---" non-blank line, stop.
			if strings.TrimSpace(line) != "---" && strings.TrimSpace(line) != "" {
				// No frontmatter present.
				return nil, fmt.Errorf("frontmatter not found in %s", filePath)
			}

		case insideBlock:
			if strings.TrimSpace(line) == "---" {
				// Closing delimiter found — frontmatter block is complete.
				state = done
				// Stop reading; the file body is not needed.
				goto parse
			}
			// Accumulate the YAML content line.
			yamlLines = append(yamlLines, line)
		}
	}

	// Check for scanner errors (e.g. I/O failure mid-read).
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("error reading %s: %w", filePath, err)
	}

	// If we reached EOF without finding a closing "---", the frontmatter
	// block was never closed — treat this as "not found".
	if state != done {
		return nil, fmt.Errorf("frontmatter not found in %s", filePath)
	}

parse:
	// Step 2 — unmarshal the collected YAML lines.
	//
	// Unknown fields are silently ignored by github.com/goccy/go-yaml
	// (the default behaviour mirrors gopkg.in/yaml.v3).
	yamlBlock := strings.Join(yamlLines, "\n")

	var fm Frontmatter
	if err := yaml.Unmarshal([]byte(yamlBlock), &fm); err != nil {
		return nil, fmt.Errorf("error parsing frontmatter in %s: %w", filePath, err)
	}

	return &fm, nil
}
